# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  encoding: utf8
  #reconnect: true
  port: 3306
  pool: 10
  socket: /var/run/mysqld/mysqld.sock
  adapter: mysql2
  #use when remote db source
  username: certassure_db
  password: Zounds1999
  host: 107.21.244.70
  database: www_cert_assure_production
#  else
#  username: ssl_db
#  password: kama2jama2
#  database: certassure_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: certassure_com_test
  pool: 5
  username: ssl_db
  password: kama2jama2
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: certassure_com_production
  host: 174.129.35.108
  pool: 5
  username: ssl_db
  password: kama2jama2
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test
