# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  # Stripe
  stripe_publishable_key: <%= ENV["STRIPE_TEST_PUBLISHABLE_KEY"] %>
  stripe_secret_key:      <%= ENV["STRIPE_TEST_SECRET_KEY"] %>
  
  # Paypal Express
  paypal_username:        <%= ENV["PAYPAL_TEST_USERNAME"] %>
  paypal_password:        <%= ENV["PAYPAL_TEST_PASSWORD"] %>
  paypal_signature:       <%= ENV["PAYPAL_TEST_SIGNATURE"] %>
  
  # Authorize.net
  authorize_net_key:        <%= ENV["AUTHORIZE_NET_TEST_KEY"] %>
  authorize_net_trans_id:   <%= ENV["AUTHORIZE_NET_TEST_TRANS_ID"] %>
  authorize_net_client_key: <%= ENV["AUTHORIZE_NET_TEST_CLIENT_KEY"] %>

  # Comodo API
  comodo_api_username: <%= ENV["COMODO_API_TEST_USERNAME"] %>
  comodo_api_password: <%= ENV["COMODO_API_TEST_PASSWORD"] %>

  # EJBCA API clientAuth
  ejbca_development_client_auth_key:  <%= ENV["EJBCA_DEVELOPMENT_CLIENT_AUTH_KEY"] %>
  ejbca_development_client_auth_cert: <%= ENV["EJBCA_DEVELOPMENT_CLIENT_AUTH_CERT"] %>

  # Twilio API Key
  twilio_api_key: <%= ENV["TWILIO_API_KEY"] %>

all: &all
  # JPMorgan Chase Bank
  ssl_routing_number: <%= ENV["SSL_ROUTING_NUMBER"] %>
  ssl_account_number: <%= ENV["SSL_ACCOUNT_NUMBER"] %>

  # CDNify Reseller API Key
  cdnify_reseller_api_key: <%= ENV["CDNIFY_RESELLER_API_KEY"] %>

  # CDNify User (admin role) API Key
  cdnify_admin_user_api_key: <%= ENV["CDNIFY_ADMIN_USER_API_KEY"] %>
  
  # DUO
  duo_integration_key:  <%= ENV["DUO_INTEGRATION_KEY"] %>
  duo_secret_key:       <%= ENV["DUO_SECRET_KEY"] %>
  duo_application_key:  <%= ENV["DUO_APPLICATION_KEY"] %>
  duo_api_hostname:     <%= ENV["DUO_API_HOSTNAME"] %>

  # DUO ACCOUNT FOR SYSTEM ADMINS
  duo_system_admins_integration_key:  <%= ENV["DUO_SYSADMIN_INTEGRATION_KEY"] %>
  duo_system_admins_secret_key:       <%= ENV["DUO_SYSADMIN_SECRET_KEY"] %>
  duo_system_admins_application_key:  <%= ENV["DUO_SYSADMIN_APPLICATION_KEY"] %>
  duo_system_admins_api_hostname:     <%= ENV["DUO_SYSADMIN_API_HOSTNAME"] %>

  # SSL.com CA Host
  sslcom_ca_host:       <%= ENV["SSLCOM_CA_HOST"] %>
  sslcom_ca_admin_host: <%= ENV["SSLCOM_CA_ADMIN_HOST"] %>

  # CAA Check Directory and Log
  caa_check_path:     <%= ENV["CAA_CHECK_PATH"] %>
  caa_check_log_path: <%= ENV["CAA_CHECK_LOG_PATH"] %>

  # Recaptcha Site and Secret Key
  recaptcha_site_key:   <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  
  # AWS S3
  s3_access_key_id:     <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  s3_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  s3_bucket:            <%= ENV.fetch("S3_BUCKET_NAME") %>
  s3_avatar_bucket:     <%= ENV.fetch("S3_AVATAR_BUCKET_NAME") %>
  s3_region:            <%= ENV.fetch("AWS_DEFAULT_REGION") %>

  # EJBCA API clientAuth
  ejbca_development_client_auth_key:  <%= ENV["EJBCA_DEVELOPMENT_CLIENT_AUTH_KEY"] %>
  ejbca_development_client_auth_cert: <%= ENV["EJBCA_DEVELOPMENT_CLIENT_AUTH_CERT"] %>
  
development:
  <<: *common
  <<: *all
  secret_key_base: c16c0552f6cb737d71f1e62c35d87ef44dbaf55cf4979742b608b7570b415e9993a7b41c3991b4dec8b1e9b5e7a23e5d85da8ac1a0775ba3f3b78fb5d8ec3d63

qa:
  <<: *common
  <<: *all
  secret_key_base: 67346c2e2fcb314678d1d9082d3f81825683f782899dc8907766a870308fb16d8d3e56c5cf6a3261d3b3738b15b82257aeec80666f227e1d95a1708acab45b29 

test:
  <<: *common
  <<: *all
  secret_key_base: a1aa1e7ef92702fca3b4cbe324d5ded38b906ebf30d85fbd754a966ed596c50b75fdaef569ce07e1baa85b5a01df56ce2b66b7e55bc55e99d8f1c0190d887cad
    
production:
  <<: *all
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  
  # Stripe
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key:      <%= ENV["STRIPE_SECRET_KEY"] %>
  
  # Paypal Express
  paypal_username:        <%= ENV["PAYPAL_PROD_USERNAME"] %>
  paypal_password:        <%= ENV["PAYPAL_PROD_PASSWORD"] %>
  paypal_signature:       <%= ENV["PAYPAL_PROD_SIGNATURE"] %>
  
  # Authorize.net
  authorize_net_key:        <%= ENV["AUTHORIZE_NET_PROD_KEY"] %>
  authorize_net_trans_id:   <%= ENV["AUTHORIZE_NET_PROD_TRANS_ID"] %>
  authorize_net_client_key: <%= ENV["AUTHORIZE_NET_PROD_CLIENT_KEY"] %>

  # Comodo API
  comodo_api_username: <%= ENV["COMODO_API_USERNAME"] %>
  comodo_api_password: <%= ENV["COMODO_API_PASSWORD"] %>

  ejbca_staging_client_auth_key:      <%= ENV["EJBCA_STAGING_CLIENT_AUTH_KEY"] %>
  ejbca_staging_client_auth_cert:     <%= ENV["EJBCA_STAGING_CLIENT_AUTH_CERT"] %>
  ejbca_production_client_auth_key:   <%= ENV["EJBCA_PRODUCTION_CLIENT_AUTH_KEY"] %>
  ejbca_production_client_auth_cert:  <%= ENV["EJBCA_PRODUCTION_CLIENT_AUTH_CERT"] %>
